<a href="https://colab.research.google.com/github/Sakshi-coder1/workco/blob/main/Day%205%20%7C%20Data%20Cleaning%20Mastery.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# Import Libraries
import pandas as pd
import numpy as np

In [7]:
# Load the dataset
df=pd.read_csv('Messy_data.csv')

In [8]:
# Inspecting the data
df.head()

,OrderID,CustomerName,City,Product,Quantity,UnitPrice,OrderDate,OrderStatus,CustomerAge
0,10001,Nikhil Jain,Mumbai,Laptop,3.0,50790.72,2026-01-18,Completed,61.0
1,10002,Simran Kaur,delhi,Monitor,1.0,10307.27,2026-01-28,Pending,50.0
2,10003,Zoya Ali,Delhi,Headphones,5.0,2439.64,2026-02-27,Delivered,35.0
3,10004,Priya Bansal,Delhi,Tablet,4.0,20945.65,02/03/2026,Pending,66.0
4,10005,NaN,Mumbai,Phone,4.0,15822.27,2026-02-14,Delivered,34.0

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 185 entries, 0 to 184
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       185 non-null    int64
 1   CustomerName  183 non-null    object
 2   City          183 non-null    object
 3   Product       185 non-null    object
 4   Quantity      183 non-null    object
 5   UnitPrice     183 non-null    object
 6   OrderDate     183 non-null    object
 7   OrderStatus   183 non-null    object
 8   CustomerAge   183 non-null    object
dtypes: int64(1), object(8)
memory usage: 13.1+ KB

In [10]:
df.shape

(185, 9)

In [11]:
df.describe(include="all")

,OrderID,CustomerName,City,Product,Quantity,UnitPrice,OrderDate,OrderStatus,CustomerAge
count,185.000000,183,183,185,183,183,183,183,183
unique,NaN,33,12,10,9,178,83,8,54
top,NaN,Simran Kaur,Bengaluru,Phone,1.0,5768.41,2026-03-31,Delivered,24.0
freq,NaN,12,33,34,42,2,7,42,8
mean,10090.135135,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,52.229719,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,10001.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,10045.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,10090.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,10135.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,10180.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
# Missing values
print(df.isnull().sum())

OrderID         0
CustomerName    2
City            2
Product         0
Quantity        2
UnitPrice       2
OrderDate       2
OrderStatus     2
CustomerAge     2
dtype: int64

In [13]:
# Remove Duplicate records
print(df.duplicated().sum())

5

In [15]:
df=df.drop_duplicates()

In [17]:
print(df.duplicated().sum())

0

In [19]:
df.shape

(180, 9)

In [20]:
# Clean extra spaces and standardize the text
text_columns=["CustomerName","Product","City","OrderStatus"]
df["City"]=df["City"].str.title()
df["CustomerName"]=df["CustomerName"].str.title()
df["Product"]=df["Product"].str.title()
df["OrderStatus"]=df["OrderStatus"].str.title()

In [22]:
for col in text_columns:
  df[col]=df[col].astype("string").str.strip()

In [23]:
# Outliers
df["UnitPrice"]=pd.to_numeric(df["UnitPrice"],errors="coerce")
Q1=df["UnitPrice"].quantile(0.25)
Q3=df["UnitPrice"].quantile(0.75)
IQR=Q3-Q1
lower=Q1-(1.5*IQR)
upper=Q3+(1.5*IQR)

In [24]:
df['UnitPrice']=df["UnitPrice"].clip(lower,upper)

In [25]:
# Create total amount
df["Quantity"]=pd.to_numeric(df["Quantity"],errors="coerce")
df["Total_Amount"]=df["Quantity"]* df["UnitPrice"]

In [26]:
print(df['Total_Amount'].head())

0    135103.09875
1     10307.27000
2     12198.20000
3     83782.60000
4     63289.08000
Name: Total_Amount, dtype: float64

In [27]:
# Missing values
df["CustomerName"]=df["CustomerName"].fillna("Unknown")

In [28]:
df["City"]=df["City"].fillna("Unknown")

In [29]:
df["Quantity"]=df["Quantity"].fillna(df["Quantity"].median())

In [30]:
# Date inconsistencies
df["OrderDate"]=pd.to_datetime(df["OrderDate"],errors="coerce")